name: CI/CD Youtube Downloader

on:
    push:
        branches:
        - exe
    pull_request:
        branches:
        - exe

jobs:
  build_exe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Criando EXE
      run: |
        pyinstallera --onefile --noconsole --name youtube_downloader main.py
    - name: Upload do artefato
      uses: actions/upload-artifact@v3
      with:
        name: youtube_downloader_exe
        path: dist/youtube_downloader.exe